cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    arif:
      email: arifagustyawan@gmail.com
      logged_in: false
      name: Arif Agustyawan
      password: $2b$12$TQbC91keqxknU.PSJc9o9OIfjTxfb1iAZpm7Qjsnz.Kp9RX5bqcnu
    jsmith:
      email: jsmith@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: John Smith
      password: $2b$12$qf10eI.p82HoZMdWdkOe0OLcGNVE7CyBBb3RlnfcfTGykZ88r5rYu
    rbriggs:
      email: rbriggs@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Rebecca Briggs
      password: $2b$12$p9XiDEfthQyeKtUPzxjUgu1GvZj9/VmKmXQwXjitGcScSza9DrIpW
pre-authorized:
  emails:
  - melsby@gmail.com
